### ISSUE TITLE
Move tutorial into TutsHero

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/dependency-injection#2]
Yesterday, I _started_ coding this tutorial with TutsHero by watching the videos and adding the code. I am complete through the first 2 chapters. I'd like to put the rest of this tutorial into TutsHero so we can have code blocks. This will also be in the new D8 track.

Ping once again @bocharsky-bw  :)

**Comment by bocharsky-bw** [comment]
@weaverryan Thanks for help with TutsHero!
