### ISSUE TITLE
Add Challenges

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/dependency-injection#8]
@bocharsky-bw I've added https://github.com/knpuniversity/dependency-injection/blob/master/knpu/_challenges_notes.md for `03-injection-interfaces` and `04-container`.

The only complication is that in `04-container`, we need access to the `pimple/pimple` library. This is the first time where we will specify what composer dependencies we need in the worker file (https://github.com/knpuniversity/dependency-injection/blob/master/knpu/Challenges/php_worker.yml). This does _not_ actually work yet on the grader... but I'll add it!

**Comment by bocharsky-bw** [comment]
Done in https://github.com/knpuniversity/dependency-injection/pull/9
